{
  "path": "android.system",
  "name": "ErrnoException",
  "values": [
    {
      "type": "ctor",
      "ctor": "<init>(functionName: String!, errno: Int)\n            Constructs an instance with the given function name and errno value."
    },
    {
      "type": "ctor",
      "ctor": "<init>(functionName: String!, errno: Int, cause: Throwable!)\n            Constructs an instance with the given function name, errno value, and cause."
    },
    {
      "type": "method",
      "status": "public"
    },
    {
      "type": "method",
      "status": "public",
      "identifier": "IOException",
      "code": "rethrowAsIOException()",
      "desc": "Throws an IOException with a message based on getMessage() and with this instance as the cause."
    },
    {
      "type": "method",
      "status": "public",
      "identifier": "SocketException",
      "code": "rethrowAsSocketException()",
      "desc": "Throws a SocketException with a message based on getMessage() and with this instance as the cause."
    }
  ]
}